import type { MemoryEngineMock } from '@/features/memory/types/memory.types'

export function getMemoryEngineMock(): MemoryEngineMock {
  return {
    insight: {
      title: 'Contexto que começa a trabalhar por você',
      message: 'O LifeOS percebeu que sua constância melhora quando você registra seu dia à noite.',
      recommendation: 'Futuramente, esse sinal poderá ajustar lembretes, planos e sugestões sem depender de IA acoplada à interface.',
    },
    memories: [
      {
        id: 'memory-main-dream',
        title: 'Sonho principal',
        description: 'Correr 10 km aparece como objetivo físico mais acionável no ciclo atual.',
        category: 'sonho',
        origin: 'Dream Engine',
        confidence: 'alta',
        updatedAt: 'Hoje',
      },
      {
        id: 'memory-current-routine',
        title: 'Rotina atual',
        description: 'O usuário responde melhor a blocos curtos de execução pela manhã e revisão à noite.',
        category: 'rotina',
        origin: 'Life Engine',
        confidence: 'média',
        updatedAt: 'Ontem',
      },
      {
        id: 'memory-main-friction',
        title: 'Maior dificuldade',
        description: 'Descanso e consistência de sono ainda oscilam quando há excesso de metas no mesmo dia.',
        category: 'saúde',
        origin: 'Diário',
        confidence: 'média',
        updatedAt: '2 dias atrás',
      },
      {
        id: 'memory-strong-habits',
        title: 'Hábitos fortes',
        description: 'Treinos, hidratação e registros rápidos têm boa aderência quando conectados a uma meta física.',
        category: 'hábito',
        origin: 'Check-in',
        confidence: 'alta',
        updatedAt: 'Esta semana',
      },
      {
        id: 'memory-risk-habits',
        title: 'Hábitos em risco',
        description: 'Leitura e estudo caem quando não existe horário fixo definido.',
        category: 'estudo',
        origin: 'Metas',
        confidence: 'média',
        updatedAt: 'Esta semana',
      },
      {
        id: 'memory-training-preference',
        title: 'Preferência de treino',
        description: 'Prefere treinos objetivos, com divisão simples e corrida leve como recuperação ativa.',
        category: 'treino',
        origin: 'Check-in',
        confidence: 'alta',
        updatedAt: 'Hoje',
      },
      {
        id: 'memory-spiritual-focus',
        title: 'Foco espiritual',
        description: 'Gratidão, oração e leitura bíblica aparecem como base de direção e estabilidade emocional.',
        category: 'espiritualidade',
        origin: 'Perfil',
        confidence: 'média',
        updatedAt: '3 dias atrás',
      },
      {
        id: 'memory-career-goal',
        title: 'Objetivo profissional',
        description: 'Completar um curso e aplicar um projeto prático é o foco profissional mais próximo.',
        category: 'meta',
        origin: 'Dream Engine',
        confidence: 'média',
        updatedAt: 'Hoje',
      },
    ],
    timeline: [
      {
        id: 'timeline-1',
        date: 'Hoje',
        title: 'Objetivo físico identificado',
        description: 'Correr 10 km foi marcado como sonho executável do ciclo atual.',
        source: 'Dream Engine',
      },
      {
        id: 'timeline-2',
        date: 'Ontem',
        title: 'Padrão de rotina observado',
        description: 'Revisões noturnas melhoram clareza do dia seguinte.',
        source: 'Life Engine',
      },
      {
        id: 'timeline-3',
        date: 'Esta semana',
        title: 'Sinal de treino consolidado',
        description: 'Check-ins indicam preferência por treinos diretos e corrida leve.',
        source: 'Check-in',
      },
      {
        id: 'timeline-4',
        date: '3 dias atrás',
        title: 'Foco espiritual registrado',
        description: 'Gratidão e oração aparecem como âncoras importantes de direção.',
        source: 'Perfil',
      },
    ],
  }
}
