import type { DreamEngineMock } from '@/features/dreams/types/dream.types'

export function getDreamEngineMock(): DreamEngineMock {
  return {
    featuredDreamId: 'dream-run-10k',
    insight: {
      title: 'Seu sonho já tem forma',
      message: 'Você está a 3 ações de transformar esse sonho em uma meta real.',
      signal: 'Dream Engine mockado, pronto para IA, hábitos, calendário e Supabase.',
    },
    dreams: [
      {
        id: 'dream-english',
        title: 'Estudar inglês por 6 meses',
        why: 'Abrir portas profissionais e viajar com mais liberdade.',
        deadline: 'Dezembro de 2026',
        lifeArea: 'Idiomas',
        priority: 'media',
        progress: 34,
        status: 'active',
        nextAction: 'Fazer 20 minutos de listening hoje.',
        plan: {
          annualGoal: 'Conversar por 30 minutos em inglês com confiança.',
          monthlyGoal: 'Completar 16 sessões de estudo.',
          weeklyGoal: 'Estudar 4 vezes na semana.',
          dailyHabit: 'Ouvir inglês por 20 minutos.',
          nextStep: 'Escolher um episódio curto para assistir sem legenda.',
        },
      },
      {
        id: 'dream-health',
        title: 'Criar uma rotina saudável',
        why: 'Ter energia, clareza mental e constância para sustentar meus projetos.',
        deadline: 'Próximos 90 dias',
        lifeArea: 'Saúde',
        priority: 'alta',
        progress: 42,
        status: 'active',
        nextAction: 'Dormir antes das 23h hoje.',
        plan: {
          annualGoal: 'Manter uma rotina sólida de sono, treino e alimentação.',
          monthlyGoal: 'Treinar 12 vezes e dormir melhor em 20 noites.',
          weeklyGoal: 'Completar 3 treinos e planejar refeições base.',
          dailyHabit: 'Beber água e fazer check-in de energia.',
          nextStep: 'Preparar a primeira refeição saudável de amanhã.',
        },
      },
      {
        id: 'dream-books',
        title: 'Ler 12 livros este ano',
        why: 'Aumentar repertório, disciplina e clareza para tomar melhores decisões.',
        deadline: 'Dezembro de 2026',
        lifeArea: 'Leitura',
        priority: 'media',
        progress: 25,
        status: 'active',
        nextAction: 'Ler 10 páginas antes de dormir.',
        plan: {
          annualGoal: 'Finalizar 12 livros no ano.',
          monthlyGoal: 'Ler 1 livro por mês.',
          weeklyGoal: 'Completar 60 páginas na semana.',
          dailyHabit: 'Ler 10 páginas por dia.',
          nextStep: 'Escolher o livro do mês e ler hoje.',
        },
      },
      {
        id: 'dream-savings',
        title: 'Economizar R$ 10.000',
        why: 'Criar segurança financeira e margem para decisões melhores.',
        deadline: 'Dezembro de 2026',
        lifeArea: 'Finanças',
        priority: 'alta',
        progress: 22,
        status: 'at_risk',
        nextAction: 'Separar R$ 200 esta semana.',
        plan: {
          annualGoal: 'Economizar R$ 10.000 em 12 meses.',
          monthlyGoal: 'Guardar pelo menos R$ 835 por mês.',
          weeklyGoal: 'Revisar gastos e reservar a meta semanal.',
          dailyHabit: 'Registrar gastos essenciais do dia.',
          nextStep: 'Agendar a transferência da próxima reserva.',
        },
      },
      {
        id: 'dream-run-10k',
        title: 'Correr 10 km',
        why: 'Provar para mim mesmo que consigo construir resistência com consistência.',
        deadline: 'Outubro de 2026',
        lifeArea: 'Corrida',
        priority: 'media',
        progress: 56,
        status: 'active',
        nextAction: 'Agendar uma corrida leve amanhã.',
        plan: {
          annualGoal: 'Completar uma prova de 10 km.',
          monthlyGoal: 'Correr 3 vezes por semana.',
          weeklyGoal: 'Completar 12 km na semana.',
          dailyHabit: 'Alongamento + hidratação.',
          nextStep: 'Agendar uma corrida leve amanhã.',
        },
      },
      {
        id: 'dream-course',
        title: 'Completar um curso',
        why: 'Avançar profissionalmente com uma habilidade prática e aplicável.',
        deadline: 'Próximos 6 meses',
        lifeArea: 'Educação',
        priority: 'media',
        progress: 48,
        status: 'active',
        nextAction: 'Assistir a próxima aula hoje.',
        plan: {
          annualGoal: 'Concluir o curso e aplicar o projeto final.',
          monthlyGoal: 'Completar um módulo por mês.',
          weeklyGoal: 'Estudar 3 aulas por semana.',
          dailyHabit: 'Separar 30 minutos de estudo focado.',
          nextStep: 'Abrir a próxima aula e fazer anotações.',
        },
      },
      {
        id: 'dream-spiritual-life',
        title: 'Fortalecer minha rotina espiritual',
        why: 'Viver com mais presença, gratidão, oração e direção.',
        deadline: 'Próximos 90 dias',
        lifeArea: 'Fé',
        priority: 'alta',
        progress: 64,
        status: 'paused',
        nextAction: 'Separar 10 minutos para oração hoje.',
        plan: {
          annualGoal: 'Construir uma rotina espiritual consistente.',
          monthlyGoal: 'Ler e refletir em 20 dias do mês.',
          weeklyGoal: 'Reservar 4 momentos de oração e leitura.',
          dailyHabit: 'Gratidão, oração e um trecho bíblico.',
          nextStep: 'Escolher o horário fixo de amanhã.',
        },
      },
    ],
  }
}
