import type { EvolutionHistory } from '../types/evolution.types'

export async function getEvolutionHistoryMock(): Promise<EvolutionHistory> {
  return {
    periods: [
      {
        id: 'today',
        label: 'Hoje',
        range: 'daily',
        lifeScore: 74,
        habitsCompleted: 5,
        workouts: 1,
        runs: 0,
        checkIns: 6,
        streak: 8,
        summary: 'Dia consistente, com treino registrado e bons sinais de rotina.',
        comparison: '+6 pts vs. ontem',
      },
      {
        id: 'week',
        label: 'Semana',
        range: 'weekly',
        lifeScore: 69,
        habitsCompleted: 28,
        workouts: 4,
        runs: 2,
        checkIns: 34,
        streak: 8,
        summary: 'Semana acima da média em academia e hábitos essenciais.',
        comparison: '+11% vs. semana anterior',
      },
      {
        id: 'month',
        label: 'Mês',
        range: 'monthly',
        lifeScore: 66,
        habitsCompleted: 104,
        workouts: 15,
        runs: 7,
        checkIns: 126,
        streak: 8,
        summary: 'Mês com boa base de consistência e espaço para melhorar descanso.',
        comparison: '+4 pts vs. mês anterior',
      },
      {
        id: 'year',
        label: 'Ano',
        range: 'yearly',
        lifeScore: 71,
        habitsCompleted: 892,
        workouts: 118,
        runs: 54,
        checkIns: 1086,
        streak: 8,
        summary: 'Ano em evolução, com saúde e conhecimento puxando o progresso.',
        comparison: '+18% vs. ciclo anterior',
      },
    ],
    comparisons: [
      {
        id: 'today-vs-yesterday',
        label: 'Hoje vs. ontem',
        currentLabel: 'Hoje',
        previousLabel: 'Ontem',
        currentScore: 74,
        previousScore: 68,
        delta: 6,
        summary: 'Mais check-ins e treino concluído.',
      },
      {
        id: 'week-vs-last-week',
        label: 'Semana atual vs. anterior',
        currentLabel: 'Semana atual',
        previousLabel: 'Semana anterior',
        currentScore: 69,
        previousScore: 62,
        delta: 7,
        summary: 'Academia, hábitos e estudos em alta.',
      },
      {
        id: 'month-vs-last-month',
        label: 'Mês atual vs. anterior',
        currentLabel: 'Mês atual',
        previousLabel: 'Mês anterior',
        currentScore: 66,
        previousScore: 62,
        delta: 4,
        summary: 'Mais treinos e corridas; descanso pede atenção.',
      },
      {
        id: 'year-vs-last-year',
        label: 'Ano atual vs. anterior',
        currentLabel: 'Ano atual',
        previousLabel: 'Ano anterior',
        currentScore: 71,
        previousScore: 60,
        delta: 11,
        summary: 'Evolução consistente em saúde, rotina e conhecimento.',
      },
    ],
    gymCheckIns: [
      { id: 'gym-1', date: 'Hoje', time: '07:20', workout: 'peito e tríceps', notes: 'Carga estável, boa energia e execução controlada.', photoUrl: 'mock://storage/gym/today' },
      { id: 'gym-2', date: 'Ontem', time: '18:10', workout: 'costas e bíceps', notes: 'Foco em execução lenta e amplitude completa.', photoUrl: 'mock://storage/gym/yesterday' },
      { id: 'gym-3', date: 'Terça', time: '06:50', workout: 'pernas', notes: 'Pernas completo. Sono precisa melhorar.', photoUrl: 'mock://storage/gym/legs' },
    ],
    runCheckIns: [
      { id: 'run-1', date: 'Domingo', activityType: 'caminhada', distanceKm: 4.1, duration: '42:18', pace: '10:19/km', notes: 'Caminhada leve para recuperação ativa.', photoUrl: 'mock://storage/runs/sunday' },
      { id: 'run-2', date: 'Sábado', activityType: 'corrida', distanceKm: 5.2, duration: '31:42', pace: '6:05/km', notes: 'Corrida leve, zona confortável.', photoUrl: 'mock://storage/runs/saturday' },
      { id: 'run-3', date: 'Quarta', activityType: 'corrida', distanceKm: 3.4, duration: '19:54', pace: '5:51/km', notes: 'Ritmo progressivo no final.', photoUrl: 'mock://storage/runs/wednesday' },
    ],
    activitySession: {
      id: 'activity-mock',
      mode: 'corrida',
      status: 'mock-ready',
      duration: '24:18',
      distanceKm: 3.9,
      pace: '6:14/km',
      speedKmh: 9.6,
      altitudeGainM: 0,
      calories: 246,
      mapPreview: 'Rota mockada preparada para Geolocation API, PWA, iPhone e Android.',
      routeName: 'Parque da Cidade',
      startedAt: '06:42',
    },
    coachInsights: [
      { id: 'coach-1', category: 'treino', title: 'Divisão sugerida', description: 'Mantenha peito + tríceps, costas + bíceps e pernas como base semanal.' },
      { id: 'coach-2', category: 'descanso', title: 'Recuperação', description: 'Inclua um bloco leve de mobilidade após dias de corrida ou pernas.' },
      { id: 'coach-3', category: 'hábitos', title: 'Próximo hábito', description: 'Aumente água e sono antes de subir volume de treino.' },
    ],
    reminders: [
      { id: 'rem-1', category: 'Saúde', message: 'Você ainda não atingiu sua meta de água.', timing: '14:30', tone: 'incentivo' },
      { id: 'rem-2', category: 'Academia', message: 'Hoje é dia de treino.', timing: '07:00', tone: 'incentivo' },
      { id: 'rem-3', category: 'Estudos', message: 'Hora do aprendizado.', timing: '20:00', tone: 'elogio' },
      { id: 'rem-4', category: 'Motivação', message: 'Reduzir notificações no fim da noite.', timing: '22:30', tone: 'reduzir frequência' },
    ],
    dailyVerse: {
      reference: 'Provérbios 16:3',
      text: 'Consagre ao Senhor tudo o que você faz, e os seus planos serão bem-sucedidos.',
      gratitudePrompt: 'Registre uma coisa pela qual você é grato hoje.',
      prayerPrompt: 'Separe dois minutos para oração antes da próxima ação.',
      enabled: true,
      frequency: 'diária',
    },
    analytics: [
      { id: 'ana-1', title: 'Consistência semanal', metric: '+11%', trend: 'up', description: 'Mais check-ins do que na semana anterior.' },
      { id: 'ana-2', title: 'Treinos concluídos', metric: '4/5', trend: 'stable', description: 'Volume estável; próxima melhoria é progressão de carga.' },
      { id: 'ana-3', title: 'Corrida', metric: '8.6 km', trend: 'up', description: 'Distância semanal crescendo de forma sustentável.' },
    ],
  }
}
